# Generated by Django 2.2.5 on 2020-03-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_count', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='eye_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='count',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='count',
            name='face_count',
            field=models.IntegerField(),
        ),
    ]
