# Generated by Django 2.2.5 on 2020-03-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_count', '0002_auto_20200323_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='finish_unix_datetime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='count',
            name='start_unix_datetime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
