# Generated by Django 2.2.5 on 2020-03-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_count', '0003_auto_20200323_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='count',
            name='start_date',
        ),
        migrations.AddField(
            model_name='count',
            name='data_title',
            field=models.CharField(default='カウント', max_length=50),
        ),
    ]
