# Generated by Django 2.2.5 on 2020-03-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_count', '0004_auto_20200324_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='face_count',
            field=models.IntegerField(default=0),
        ),
    ]
