# Generated by Django 2.1.1 on 2020-04-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_count', '0006_usagelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelist',
            name='list_link',
            field=models.TextField(max_length=100),
        ),
    ]
