# Generated by Django 2.1.1 on 2020-04-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_count', '0008_auto_20200405_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelist',
            name='list_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usagelist',
            name='list_link',
            field=models.CharField(max_length=100),
        ),
    ]
