# Generated by Django 2.1.1 on 2020-04-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_count', '0009_auto_20200405_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelist',
            name='list_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
