# Generated by Django 2.1.1 on 2020-04-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_count', '0010_auto_20200405_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelist',
            name='list_link_title',
            field=models.CharField(default='タイトル', max_length=15),
        ),
    ]
