# Generated by Django 2.1.1 on 2020-04-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_count', '0012_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
