# Generated by Django 2.1.1 on 2020-04-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_count', '0013_auto_20200405_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
